### ISSUE TITLE
Create Minimum Viable Product features

### ISSUE THREAD

**Issue by wleoncio** [derecost/LOGAN#5]
Please post on this page all the _essential_ features required for the next package release.

**Comment by derecost** [comment]
Review the consistency of the function names (e.g., change "m0$DataActionsbyID" to "m0$DataActionsById"?)

**Comment by derecost** [comment]
Review the consistency of the argument names (e.g., change "starttime.vec" to "start.time.vec"?)

**Comment by derecost** [comment]
Review the consistency of the object names in the examples (e.g., change "cp025q01.startTime" to "cp025q01.start.time"?)

**Comment by derecost** [comment]
Check if it is possible to incorporate the rlang::quo() to the "m0$ConcatActions()". In this case, we avoid the user's needs to use this function in the "concat.events" object.

**Comment by derecost** [comment]
Review the "m1$TOTVar" function and try to incorporate new features (e.g., merging the data with start and end times)

**Comment by derecost** [comment]
Incorporate the "VarActionSearch" function to module 2

**Comment by derecost** [comment]
Include a new argument and use sample weights (and plausible values) into the following functions: "m1$SummaryTOTbyVar" and "m2$DescriptiveStrategy". It is recommended to have a look at the "intsvy" package for the implementation of these variables.

**Comment by wleoncio** [comment]
That's all?

**Comment by wleoncio** [comment]
All features have been added as issues grouped under the [MVP LOGAN 2.0.0 milestone](https://github.com/derecost/LOGAN/milestone/1). Once that milestone is 100% complete, we should prepare a new release.
